server:
  port: 8080
  servlet:
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true
    context-path: /pohar

spring:
  datasource:
    url: jdbc:h2:mem:pohardb
    username: sa
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui

springdoc:
  swagger-ui:
    path: /swagger-ui.html